version: '3.9'

services:
  postgres:
    image: postgres
    container_name: database_pebmed
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=pebmed
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: app_pebmed
    restart: always
    ports:
      - 3333:3333
      - 9229:9229
    volumes:
      - .:/usr/app
    links:
      - postgres
    depends_on:
      - postgres

volumes:
  pgdata:
    driver: local
